use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Ergo Node API",
        description = "REST API for the Ergo blockchain node (Rust implementation).",
        version = "5.0.0"
    ),
    tags(
        (name = "info", description = "Node information"),
        (name = "blocks", description = "Block queries and submission"),
        (name = "transactions", description = "Transaction queries and submission"),
        (name = "utxo", description = "UTXO set queries"),
        (name = "peers", description = "Peer management"),
        (name = "mining", description = "Mining operations"),
        (name = "wallet", description = "Wallet operations"),
        (name = "utils", description = "Utility endpoints"),
        (name = "emission", description = "Emission information"),
        (name = "script", description = "Script compilation and utilities"),
        (name = "node", description = "Node management"),
        (name = "blockchain", description = "Indexed blockchain queries"),
        (name = "nipopow", description = "NiPoPoW proofs")
    ),
    paths(
        // info
        super::handlers::info::info_handler,
        // blocks
        super::handlers::blocks::get_block_handler,
        super::handlers::blocks::get_blocks_at_height_handler,
        super::handlers::blocks::get_paginated_blocks_handler,
        super::handlers::blocks::get_last_headers_handler,
        super::handlers::blocks::get_chain_slice_handler,
        super::handlers::blocks::get_header_only_handler,
        super::handlers::blocks::get_block_transactions_handler,
        super::handlers::blocks::post_header_ids_handler,
        super::handlers::blocks::get_modifier_handler,
        super::handlers::blocks::post_block_handler,
        super::handlers::blocks::merkle_proof_handler,
        // transactions
        super::handlers::transactions::submit_transaction_handler,
        super::handlers::transactions::get_unconfirmed_handler,
        super::handlers::transactions::get_unconfirmed_size_handler,
        super::handlers::transactions::get_unconfirmed_by_id_handler,
        super::handlers::transactions::check_transaction_handler,
        super::handlers::transactions::submit_transaction_bytes_handler,
        super::handlers::transactions::check_transaction_bytes_handler,
        super::handlers::transactions::pool_histogram_handler,
        super::handlers::transactions::get_fee_handler,
        super::handlers::transactions::wait_time_handler,
        super::handlers::transactions::head_unconfirmed_handler,
        super::handlers::transactions::get_unconfirmed_tx_ids_handler,
        super::handlers::transactions::post_by_transaction_ids_handler,
        super::handlers::transactions::get_unconfirmed_inputs_by_box_id_handler,
        super::handlers::transactions::get_unconfirmed_output_by_box_id_handler,
        super::handlers::transactions::get_unconfirmed_outputs_by_token_id_handler,
        super::handlers::transactions::post_unconfirmed_by_ergo_tree_handler,
        super::handlers::transactions::post_unconfirmed_outputs_by_ergo_tree_handler,
        super::handlers::transactions::post_unconfirmed_outputs_by_registers_handler,
        // utxo
        super::handlers::utxo::utxo_by_id_handler,
        super::handlers::utxo::utxo_by_id_binary_handler,
        super::handlers::utxo::utxo_with_pool_by_id_handler,
        super::handlers::utxo::utxo_with_pool_by_ids_handler,
        super::handlers::utxo::utxo_with_pool_by_id_binary_handler,
        super::handlers::utxo::utxo_genesis_handler,
        super::handlers::utxo::utxo_snapshots_info_handler,
        super::handlers::utxo::utxo_boxes_binary_proof_handler,
        // peers
        super::handlers::peers::peers_connected_handler,
        super::handlers::peers::peers_map_handler,
        super::handlers::peers::peers_all_handler,
        super::handlers::peers::peers_blacklisted_handler,
        super::handlers::peers::peers_connect_handler,
        super::handlers::peers::peers_status_handler,
        super::handlers::peers::peers_sync_info_handler,
        super::handlers::peers::peers_track_info_handler,
        // mining
        super::handlers::mining::mining_candidate_handler,
        super::handlers::mining::mining_candidate_with_txs_handler,
        super::handlers::mining::mining_solution_handler,
        super::handlers::mining::mining_reward_address_handler,
        super::handlers::mining::mining_reward_pubkey_handler,
        // utils
        super::handlers::utils::validate_address_handler,
        super::handlers::utils::validate_address_post_handler,
        super::handlers::utils::raw_to_address_handler,
        super::handlers::utils::address_to_raw_handler,
        super::handlers::utils::ergo_tree_to_address_handler,
        super::handlers::utils::ergo_tree_to_address_post_handler,
        super::handlers::utils::seed_handler,
        super::handlers::utils::seed_with_length_handler,
        super::handlers::utils::blake2b_hash_handler,
        // emission
        super::handlers::emission::emission_handler,
        super::handlers::emission::emission_scripts_handler,
        // script
        super::handlers::script::script_address_to_tree_handler,
        super::handlers::script::script_address_to_bytes_handler,
        super::handlers::script::script_p2s_address_handler,
        super::handlers::script::script_p2sh_address_handler,
        super::handlers::script::script_compile_handler,
        super::handlers::script::script_execute_with_context_handler,
        // node
        super::handlers::node::node_shutdown_handler,
        // blockchain
        super::handlers::blockchain::indexed_height_handler,
        super::handlers::blockchain::blockchain_tx_by_id_handler,
        super::handlers::blockchain::blockchain_tx_by_index_handler,
        super::handlers::blockchain::blockchain_txs_by_address_post_handler,
        super::handlers::blockchain::blockchain_txs_by_address_get_handler,
        super::handlers::blockchain::blockchain_tx_range_handler,
        super::handlers::blockchain::blockchain_box_by_id_handler,
        super::handlers::blockchain::blockchain_box_by_index_handler,
        super::handlers::blockchain::blockchain_boxes_by_token_handler,
        super::handlers::blockchain::blockchain_unspent_boxes_by_token_handler,
        super::handlers::blockchain::blockchain_boxes_by_address_post_handler,
        super::handlers::blockchain::blockchain_boxes_by_address_get_handler,
        super::handlers::blockchain::blockchain_unspent_boxes_by_address_post_handler,
        super::handlers::blockchain::blockchain_unspent_boxes_by_address_get_handler,
        super::handlers::blockchain::blockchain_boxes_by_template_handler,
        super::handlers::blockchain::blockchain_unspent_boxes_by_template_handler,
        super::handlers::blockchain::blockchain_box_range_handler,
        super::handlers::blockchain::blockchain_boxes_by_ergo_tree_handler,
        super::handlers::blockchain::blockchain_unspent_boxes_by_ergo_tree_handler,
        super::handlers::blockchain::blockchain_token_by_id_handler,
        super::handlers::blockchain::blockchain_tokens_handler,
        super::handlers::blockchain::blockchain_balance_post_handler,
        super::handlers::blockchain::blockchain_balance_get_handler,
        super::handlers::blockchain::blockchain_block_by_header_id_handler,
        super::handlers::blockchain::blockchain_block_by_header_ids_handler,
        // nipopow
        super::handlers::nipopow::popow_header_by_id_handler,
        super::handlers::nipopow::popow_header_by_height_handler,
        super::handlers::nipopow::nipopow_proof_handler,
        super::handlers::nipopow::nipopow_proof_at_handler,
    ),
    components(schemas(
        super::NodeInfoResponse,
        super::PowSolutionsResponse,
        super::HeaderResponse,
        super::BlockResponse,
        super::TransactionResponse,
        super::InputResponse,
        super::SpendingProofResponse,
        super::DataInputResponse,
        super::OutputResponse,
        super::AssetResponse,
        super::ExtensionResponse,
        super::BlockTransactionsResponse,
        super::PeerResponse,
        super::PeerMapEntry,
        super::TxSubmitRequest,
        super::TxSubmitResponse,
        super::MempoolSizeResponse,
        super::ModifierResponse,
        super::ApiError,
        super::PeerStatusResponse,
        super::UnconfirmedOutputResponse,
        super::SpendingInputResponse,
        super::MiningCandidateResponse,
        super::CandidateWithTxsResponse,
        super::RewardAddressResponse,
        super::RewardPublicKeyResponse,
        super::AddressValidationResponse,
        super::MerkleProofResponse,
        super::EmissionScriptsResponse,
        super::HistogramBinResponse,
        super::FeeEstimateResponse,
        super::WaitTimeResponse,
        super::IndexedHeightResponse,
        super::IndexedErgoBoxResponse,
        super::TokenAmountResponse,
        super::IndexedErgoTransactionResponse,
        super::PaginatedTxResponse,
        super::PaginatedBoxResponse,
        super::IndexedTokenResponse,
        super::BalanceResponse,
        super::BalanceInfoResponse,
        super::TokenBalanceResponse,
        super::IndexedBlockResponse,
        super::PoPowHeaderResponse,
        super::NipopowProofResponse,
        super::ScriptCompileRequest,
        super::ScriptCompileResponse,
        super::ScriptFullCompileResponse,
        crate::geoip::GeoInfo,
        crate::mining::MiningSolution,
    ))
)]
pub struct ApiDoc;
