//! Runtime-oracle parity check for the prune formula
//! `compute_minimal_full_block_height`.
//!
//! Ground truth is `test-vectors/mode3-pruning/runtime-vectors.json`,
//! generated by `test-vectors/mode3-pruning/oracle-harness/run.sh`,
//! which drives the upstream Scala `FullBlockPruningProcessor`
//! against each input tuple and captures its actual output.
//!
//! For each runtime vector, Rust MUST either:
//!   1. Match `scala_runtime_output` (convergent), OR
//!   2. Match the `rust_expected` declared in
//!      `prune-formula-vectors.json`'s `divergent_vectors` for an
//!      `id` already present in that fixture, AND the documented
//!      `scala_expected` MUST match the captured
//!      `scala_runtime_output` (otherwise the divergence drifted
//!      and the docs are stale).

#![cfg(feature = "test-helpers")]

use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use ergo_state::store::compute_minimal_full_block_height;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Inputs {
    current_min: u32,
    header_height: u32,
    blocks_to_keep: i32,
    voting_length: u32,
}

#[derive(Debug, Deserialize)]
struct RuntimeVector {
    id: String,
    inputs: Inputs,
    scala_runtime_output: u32,
}

#[derive(Debug, Deserialize)]
struct RuntimeFile {
    vectors: Vec<RuntimeVector>,
}

#[derive(Debug, Deserialize)]
struct DivergenceEntry {
    id: String,
    rust_expected: u32,
    scala_expected: u32,
}

#[derive(Debug, Deserialize)]
struct DivergenceFile {
    convergent_vectors: Vec<InputRow>,
    divergent_vectors: Vec<DivergenceEntry>,
}

#[derive(Debug, Deserialize)]
struct InputRow {
    id: String,
}

fn vectors_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root is ergo-state/..")
        .join("test-vectors/mode3-pruning")
}

fn load_runtime() -> RuntimeFile {
    let path = vectors_root().join("runtime-vectors.json");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "failed to read runtime vectors at {} (regenerate via \
             test-vectors/mode3-pruning/oracle-harness/run.sh): {e}",
            path.display()
        )
    });
    serde_json::from_slice(&bytes).expect("runtime vectors JSON must deserialize")
}

fn load_divergence_file() -> DivergenceFile {
    let path = vectors_root().join("prune-formula-vectors.json");
    let bytes = std::fs::read(&path)
        .unwrap_or_else(|e| panic!("failed to read divergence index at {}: {e}", path.display()));
    serde_json::from_slice(&bytes).expect("divergence index JSON must deserialize")
}

fn declared_ids(file: &DivergenceFile) -> HashSet<String> {
    file.convergent_vectors
        .iter()
        .map(|r| r.id.clone())
        .chain(file.divergent_vectors.iter().map(|d| d.id.clone()))
        .collect()
}

fn divergence_map(file: &DivergenceFile) -> HashMap<String, &DivergenceEntry> {
    file.divergent_vectors
        .iter()
        .map(|e| (e.id.clone(), e))
        .collect()
}

#[test]
fn runtime_vectors_cover_every_documented_input_id() {
    // Coverage check: the runtime fixture MUST contain a row for
    // every input id declared in prune-formula-vectors.json. A
    // stale or partially-regenerated runtime fixture would
    // silently reduce coverage otherwise.
    let div_file = load_divergence_file();
    let declared = declared_ids(&div_file);
    let runtime = load_runtime();
    let runtime_ids: HashSet<String> = runtime.vectors.iter().map(|v| v.id.clone()).collect();
    let missing: Vec<&String> = declared.difference(&runtime_ids).collect();
    assert!(
        missing.is_empty(),
        "runtime-vectors.json is missing {} documented input id(s): {:?}. \
         Regenerate via test-vectors/mode3-pruning/oracle-harness/run.sh.",
        missing.len(),
        missing,
    );
}

#[test]
fn rust_matches_runtime_oracle_with_documented_divergences() {
    let div_file = load_divergence_file();
    let divergences = divergence_map(&div_file);
    let runtime = load_runtime();
    assert!(
        !runtime.vectors.is_empty(),
        "runtime fixture must contain vectors",
    );

    for v in &runtime.vectors {
        let got = compute_minimal_full_block_height(
            v.inputs.current_min,
            v.inputs.header_height,
            v.inputs.blocks_to_keep,
            v.inputs.voting_length,
        );
        match divergences.get(&v.id) {
            None => {
                assert_eq!(
                    got,
                    v.scala_runtime_output,
                    "{}: Rust returned {} but Scala runtime emitted {} \
                     (inputs: current_min={}, header_height={}, \
                     blocks_to_keep={}, voting_length={})",
                    v.id,
                    got,
                    v.scala_runtime_output,
                    v.inputs.current_min,
                    v.inputs.header_height,
                    v.inputs.blocks_to_keep,
                    v.inputs.voting_length,
                );
            }
            Some(div) => {
                assert_eq!(
                    got, div.rust_expected,
                    "{}: Rust returned {} but documented rust_expected = {}",
                    v.id, got, div.rust_expected,
                );
                assert_eq!(
                    v.scala_runtime_output, div.scala_expected,
                    "{}: Scala runtime emitted {} but documented scala_expected = {} \
                     (divergence may have shifted upstream — re-check docs)",
                    v.id, v.scala_runtime_output, div.scala_expected,
                );
                assert_ne!(
                    div.rust_expected, div.scala_expected,
                    "{}: rust_expected == scala_expected; not divergent — \
                     remove from divergent_vectors",
                    v.id,
                );
            }
        }
    }
}
