//! Phase-2 Scala-differential oracle for `ergo_sigma::avl::AvlVerifier`.
//!
//! Vectors in `test-vectors/ergo-sigma/avl-proof-parity/scala_avl_vectors.json`
//! are generated by the AUTHORITATIVE Scala scrypto `BatchAVLVerifier`
//! (`scripts/avl_oracle/AvlOracle.scala`; see PROVISIONING.md). Each pins, for a
//! `(startingDigest, proof, op)`, whether Scala's `performOneOperation` succeeds
//! and the resulting `digest`. This asserts the Rust verifier agrees — the layer
//! that catches the failure modes the Phase-1 self-differential cannot:
//!
//!   * `Scala success`  => Rust op `Ok` AND `digest()` == Scala's digest. This
//!     is the REJECT-VALID guard: if any proof Scala ACCEPTS made the Rust crate
//!     panic, the guard would turn it into `Err` and this assertion would fail.
//!   * `Scala failure`  => Rust op fails (`Err`/no-op-failure). Fail-closed
//!     parity for the panic class and all malformed/wrong-op proofs.
//!
//! Per CLAUDE.md §3 the expected values come from the external Scala oracle, NOT
//! from the Rust crate — this is a genuine cross-implementation parity test.

use ergo_sigma::avl::AvlVerifier;
use std::panic::{catch_unwind, AssertUnwindSafe};

type PanicHook = Box<dyn Fn(&std::panic::PanicHookInfo<'_>) + Sync + Send>;

/// RAII silencer for the process panic hook. The wrong-op / malformed vectors
/// deliberately drive the upstream crate into panics that the wrapper catches;
/// without this the run floods stderr with caught-panic backtraces.
struct SilenceHook(Option<PanicHook>);

impl SilenceHook {
    fn install() -> Self {
        let prev = std::panic::take_hook();
        std::panic::set_hook(Box::new(|_| {}));
        SilenceHook(Some(prev))
    }
}

impl Drop for SilenceHook {
    fn drop(&mut self) {
        // NEVER call set_hook while unwinding: it panics on a panicking thread
        // (double-panic -> process abort). If we are already failing, leaving the
        // hook silenced is harmless — the run is ending.
        if !std::thread::panicking() {
            if let Some(prev) = self.0.take() {
                std::panic::set_hook(prev);
            }
        }
    }
}

const VECTORS_JSON: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../test-vectors/ergo-sigma/avl-proof-parity/scala_avl_vectors.json"
));

// ----- helpers -----

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct Vector {
    name: String,
    key_length: usize,
    value_length: Option<usize>,
    start_digest_hex: String,
    proof_hex: String,
    op: OpSpec,
    expect: Expect,
}

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct OpSpec {
    kind: String,
    key_hex: String,
    value_hex: Option<String>,
}

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expect {
    success: bool,
    digest_hex: Option<String>,
}

/// Run the vector's op against a fresh `AvlVerifier`, returning
/// `(op_succeeded, resulting_digest)`.
fn run_vector(v: &Vector) -> (bool, Option<Vec<u8>>) {
    let digest = hex::decode(&v.start_digest_hex).expect("start digest hex");
    let proof = hex::decode(&v.proof_hex).expect("proof hex");
    let key = hex::decode(&v.op.key_hex).expect("key hex");
    let value =
        v.op.value_hex
            .as_ref()
            .map(|h| hex::decode(h).expect("value hex"));

    // Construction is guarded the way every production caller guards it
    // (`cost.rs::try_make_avl_verifier`, `digest_apply`): a malformed proof can
    // panic the upstream crate at graph-rebuild time. A construction panic OR Err
    // is a fail-closed outcome (Scala: reconstructed tree None => first op
    // Failure => digest None). Op-time panics, by contrast, are contained inside
    // `AvlVerifier` itself, so the ops below need no catch here.
    let mut verifier = match catch_unwind(AssertUnwindSafe(|| {
        AvlVerifier::new(&digest, &proof, v.key_length, v.value_length)
    })) {
        Ok(Ok(w)) => w,
        _ => return (false, None),
    };

    let ok = match v.op.kind.as_str() {
        "lookup" => verifier.lookup(&key).is_ok(),
        "remove" => verifier.remove(&key).is_ok(),
        "insert" => verifier
            .insert(&key, value.as_deref().expect("insert needs value"))
            .is_ok(),
        "update" => verifier
            .update(&key, value.as_deref().expect("update needs value"))
            .is_ok(),
        other => panic!("unknown op kind {other:?} in vector {}", v.name),
    };
    (ok, verifier.digest())
}

// ----- oracle parity -----

#[test]
fn avl_verifier_matches_scala_oracle_on_all_vectors() {
    let vectors: Vec<Vector> = serde_json::from_str(VECTORS_JSON).expect("parse oracle vectors");
    assert!(!vectors.is_empty(), "no oracle vectors loaded");

    // The wrong-op / malformed vectors deliberately trigger panics the wrapper
    // catches, so silence the hook for the comparison loop — but COLLECT
    // mismatches and assert AFTER restoring the hook, so a real failure reports
    // its vector cleanly instead of being swallowed by the silent hook or
    // aborting the process via a set_hook-during-unwind double panic.
    let mut mismatches: Vec<String> = Vec::new();
    let mut accepts = 0usize;
    let mut rejects = 0usize;
    {
        let _silence = SilenceHook::install();
        for v in &vectors {
            let (rust_ok, rust_digest) = run_vector(v);
            let expected_digest = v
                .expect
                .digest_hex
                .as_ref()
                .map(|h| hex::decode(h).expect("expected digest hex"));

            if rust_ok != v.expect.success {
                mismatches.push(format!(
                    "{}: op success rust={rust_ok} scala={}",
                    v.name, v.expect.success
                ));
            } else if rust_digest != expected_digest {
                // Digest parity on BOTH accept and reject: Scala pins `digest`
                // None on every failure, and the AVL remove path decides the
                // result from the final digest — so a Rust failure that still
                // exposes Some(digest) would be a real divergence.
                mismatches.push(format!(
                    "{}: digest rust={:?} scala={:?}",
                    v.name,
                    rust_digest.as_ref().map(hex::encode),
                    expected_digest.as_ref().map(hex::encode),
                ));
            }
            if v.expect.success {
                accepts += 1;
            } else {
                rejects += 1;
            }
        }
    } // hook restored here, before any assertion

    assert!(
        mismatches.is_empty(),
        "Scala oracle parity: {} of {} vectors diverged:\n{}",
        mismatches.len(),
        vectors.len(),
        mismatches.join("\n"),
    );
    // Non-vacuity: the corpus must exercise BOTH outcomes, including the
    // wrong-op/malformed proofs that drive the Rust crate's op-time panic class.
    assert!(
        accepts > 0,
        "no Scala-accept vectors — accept-parity untested"
    );
    assert!(
        rejects > 0,
        "no Scala-reject vectors — fail-closed parity (the panic class) untested"
    );
    eprintln!("Scala oracle parity: {accepts} accepts, {rejects} rejects — all matched");
}
