include "genesis.conf"
ergo {
  directory = "scripts/devnet-mixed/.work/scala"
  node {
    headerChainDiff = 800
    mining = true
    offlineGeneration = true
    useExternalMiner = true
    miningPubKeyHex = "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
    extraIndex = true
  }
  wallet.secretStorage.secretDir = ${ergo.directory}"/wallet/keystore"
}
scorex {
  network {
    bindAddress = "127.0.0.1:19530"
    declaredAddress = "127.0.0.1:19530"
    nodeName = "conformance-scala"
    localOnly = true
    syncInterval = 1s
    syncIntervalStable = 1s
    syncStatusRefresh = 2s
    syncStatusRefreshStable = 2s
  }
  restApi {
    bindAddress = "127.0.0.1:19553"
    apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
  }
}
