[ergo]
directory = ".ergo"
network_type = "mainnet"

[ergo.node]
state_type = "utxo"
verify_transactions = true
blocks_to_keep = -1
mining = false
max_transaction_cost = 4900000
max_transaction_size = 98304
extra_index = true
checkpoint_height = 1231454
geoip_db_path = "data/GeoLite2-City.mmdb"
fast_sync = true

[ergo.chain]
protocol_version = 4
address_prefix = 0
block_interval_secs = 120
epoch_length = 1024
use_last_epochs = 8
initial_difficulty_hex = "011765000000"
genesis_state_digest_hex = "a5df145d41ab15a01e0cd3ffbab046f0d029e5412293072ad0f5827428589b9302"
genesis_id = "b0244dfc267baca974a4caee06120321562784303a8a688976ae56170e4d175b"
version2_activation_height = 417792
version2_activation_difficulty_hex = "6f98d5000000"

[ergo.chain.pow]
pow_type = "autolykos"
k = 32
n = 26

[ergo.chain.monetary]
fixed_rate_period = 525600
fixed_rate = 75000000000
founders_initial_reward = 7500000000
epoch_length = 64800
one_epoch_reduction = 3000000000
miner_reward_delay = 720

[network]
node_name = "arkadias-rusty-node-au"
app_version = "6.0.1"
agent_name = "ergo-rust"
bind_address = "0.0.0.0:9032"
declared_address = "120.88.124.73:9032"
magic_bytes = [1, 0, 2, 4]
known_peers = [
    "127.0.0.1:9030",
]

[api]
bind_address = "127.0.0.1:9055"
