[ergo]
directory = ".ergo-testnet"
network_type = "testnet"

[ergo.node]
state_type = "digest"
verify_transactions = true
blocks_to_keep = -1
mining = false
max_transaction_cost = 1000000
max_transaction_size = 98304
extra_index = false
checkpoint_height = 0

[ergo.chain]
protocol_version = 4
address_prefix = 16
block_interval_secs = 120
epoch_length = 1024
use_last_epochs = 8
initial_difficulty_hex = "01"
genesis_state_digest_hex = "cb63aa99a3060f341781d8662b58bf18b9ad258db4fe88d09f8f71cb668cad4502"
version2_activation_height = 417792
version2_activation_difficulty_hex = "20"

[ergo.chain.pow]
pow_type = "autolykos"
k = 32
n = 26

[ergo.chain.monetary]
fixed_rate_period = 525600
fixed_rate = 75000000000
founders_initial_reward = 7500000000
epoch_length = 64800
one_epoch_reduction = 3000000000
miner_reward_delay = 720

[network]
node_name = "ergo-rust-testnet"
app_version = "6.0.1"
agent_name = "ergoref"
bind_address = "0.0.0.0:9020"
magic_bytes = [2, 0, 0, 1]
known_peers = [
    "213.239.193.208:9020",
    "94.130.108.35:9020",
]

[api]
bind_address = "127.0.0.1:9052"
