//! Generated by scripts/jvm_serde_oracle/MethodTypes.scala; sigma-state 6.0.2.
use crate::sigma_type::SigmaType;
pub(super) fn signature(type_id: u8, method_id: u8) -> Option<(SigmaType, Vec<SigmaType>)> {
    use SigmaType::*;
    Some(match (type_id, method_id) {
        (2, 1) => (
            SFunc {
                t_dom: vec![SByte],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 2) => (
            SFunc {
                t_dom: vec![SByte],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 3) => (
            SFunc {
                t_dom: vec![SByte],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 4) => (
            SFunc {
                t_dom: vec![SByte],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 5) => (
            SFunc {
                t_dom: vec![SByte],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 6) => (
            SFunc {
                t_dom: vec![SByte],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 7) => (
            SFunc {
                t_dom: vec![SByte],
                t_range: Box::new(SColl(Box::new(SBoolean))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 8) => (
            SFunc {
                t_dom: vec![SByte],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 9) => (
            SFunc {
                t_dom: vec![SByte, SByte],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 10) => (
            SFunc {
                t_dom: vec![SByte, SByte],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 11) => (
            SFunc {
                t_dom: vec![SByte, SByte],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 12) => (
            SFunc {
                t_dom: vec![SByte, SInt],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (2, 13) => (
            SFunc {
                t_dom: vec![SByte, SInt],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 1) => (
            SFunc {
                t_dom: vec![SShort],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 2) => (
            SFunc {
                t_dom: vec![SShort],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 3) => (
            SFunc {
                t_dom: vec![SShort],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 4) => (
            SFunc {
                t_dom: vec![SShort],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 5) => (
            SFunc {
                t_dom: vec![SShort],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 6) => (
            SFunc {
                t_dom: vec![SShort],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 7) => (
            SFunc {
                t_dom: vec![SShort],
                t_range: Box::new(SColl(Box::new(SBoolean))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 8) => (
            SFunc {
                t_dom: vec![SShort],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 9) => (
            SFunc {
                t_dom: vec![SShort, SShort],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 10) => (
            SFunc {
                t_dom: vec![SShort, SShort],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 11) => (
            SFunc {
                t_dom: vec![SShort, SShort],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 12) => (
            SFunc {
                t_dom: vec![SShort, SInt],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (3, 13) => (
            SFunc {
                t_dom: vec![SShort, SInt],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 1) => (
            SFunc {
                t_dom: vec![SInt],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 2) => (
            SFunc {
                t_dom: vec![SInt],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 3) => (
            SFunc {
                t_dom: vec![SInt],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 4) => (
            SFunc {
                t_dom: vec![SInt],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 5) => (
            SFunc {
                t_dom: vec![SInt],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 6) => (
            SFunc {
                t_dom: vec![SInt],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 7) => (
            SFunc {
                t_dom: vec![SInt],
                t_range: Box::new(SColl(Box::new(SBoolean))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 8) => (
            SFunc {
                t_dom: vec![SInt],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 9) => (
            SFunc {
                t_dom: vec![SInt, SInt],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 10) => (
            SFunc {
                t_dom: vec![SInt, SInt],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 11) => (
            SFunc {
                t_dom: vec![SInt, SInt],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 12) => (
            SFunc {
                t_dom: vec![SInt, SInt],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (4, 13) => (
            SFunc {
                t_dom: vec![SInt, SInt],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 1) => (
            SFunc {
                t_dom: vec![SLong],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 2) => (
            SFunc {
                t_dom: vec![SLong],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 3) => (
            SFunc {
                t_dom: vec![SLong],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 4) => (
            SFunc {
                t_dom: vec![SLong],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 5) => (
            SFunc {
                t_dom: vec![SLong],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 6) => (
            SFunc {
                t_dom: vec![SLong],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 7) => (
            SFunc {
                t_dom: vec![SLong],
                t_range: Box::new(SColl(Box::new(SBoolean))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 8) => (
            SFunc {
                t_dom: vec![SLong],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 9) => (
            SFunc {
                t_dom: vec![SLong, SLong],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 10) => (
            SFunc {
                t_dom: vec![SLong, SLong],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 11) => (
            SFunc {
                t_dom: vec![SLong, SLong],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 12) => (
            SFunc {
                t_dom: vec![SLong, SInt],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (5, 13) => (
            SFunc {
                t_dom: vec![SLong, SInt],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 1) => (
            SFunc {
                t_dom: vec![SBigInt],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 2) => (
            SFunc {
                t_dom: vec![SBigInt],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 3) => (
            SFunc {
                t_dom: vec![SBigInt],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 4) => (
            SFunc {
                t_dom: vec![SBigInt],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 5) => (
            SFunc {
                t_dom: vec![SBigInt],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 6) => (
            SFunc {
                t_dom: vec![SBigInt],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 7) => (
            SFunc {
                t_dom: vec![SBigInt],
                t_range: Box::new(SColl(Box::new(SBoolean))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 8) => (
            SFunc {
                t_dom: vec![SBigInt],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 9) => (
            SFunc {
                t_dom: vec![SBigInt, SBigInt],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 10) => (
            SFunc {
                t_dom: vec![SBigInt, SBigInt],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 11) => (
            SFunc {
                t_dom: vec![SBigInt, SBigInt],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 12) => (
            SFunc {
                t_dom: vec![SBigInt, SInt],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 13) => (
            SFunc {
                t_dom: vec![SBigInt, SInt],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 14) => (
            SFunc {
                t_dom: vec![SBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (6, 15) => (
            SFunc {
                t_dom: vec![SBigInt, SUnsignedBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (7, 2) => (
            SFunc {
                t_dom: vec![SGroupElement],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (7, 3) => (
            SFunc {
                t_dom: vec![SGroupElement, SBigInt],
                t_range: Box::new(SGroupElement),
                tpe_params: vec![],
            },
            vec![],
        ),
        (7, 4) => (
            SFunc {
                t_dom: vec![SGroupElement, SGroupElement],
                t_range: Box::new(SGroupElement),
                tpe_params: vec![],
            },
            vec![],
        ),
        (7, 5) => (
            SFunc {
                t_dom: vec![SGroupElement],
                t_range: Box::new(SGroupElement),
                tpe_params: vec![],
            },
            vec![],
        ),
        (7, 6) => (
            SFunc {
                t_dom: vec![SGroupElement, SUnsignedBigInt],
                t_range: Box::new(SGroupElement),
                tpe_params: vec![],
            },
            vec![],
        ),
        (8, 1) => (
            SFunc {
                t_dom: vec![SSigmaProp],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (8, 2) => (
            SFunc {
                t_dom: vec![SSigmaProp],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 1) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 2) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 3) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 4) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 5) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 6) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(STuple(vec![SInt, SColl(Box::new(SByte))])),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 8) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SColl(Box::new(STuple(vec![SColl(Box::new(SByte)), SLong])))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 7) => (
            SFunc {
                t_dom: vec![SBox, SInt],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 9) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 10) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 11) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 12) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 13) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 14) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 15) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 16) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 17) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 18) => (
            SFunc {
                t_dom: vec![SBox],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (99, 19) => (
            SFunc {
                t_dom: vec![SBox, SInt],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![STypeVar("T".into())],
        ),
        (100, 1) => (
            SFunc {
                t_dom: vec![SAvlTree],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 2) => (
            SFunc {
                t_dom: vec![SAvlTree],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 3) => (
            SFunc {
                t_dom: vec![SAvlTree],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 4) => (
            SFunc {
                t_dom: vec![SAvlTree],
                t_range: Box::new(SOption(Box::new(SInt))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 5) => (
            SFunc {
                t_dom: vec![SAvlTree],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 6) => (
            SFunc {
                t_dom: vec![SAvlTree],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 7) => (
            SFunc {
                t_dom: vec![SAvlTree],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 8) => (
            SFunc {
                t_dom: vec![SAvlTree, SByte],
                t_range: Box::new(SAvlTree),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 9) => (
            SFunc {
                t_dom: vec![SAvlTree, SColl(Box::new(SByte)), SColl(Box::new(SByte))],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 10) => (
            SFunc {
                t_dom: vec![SAvlTree, SColl(Box::new(SByte)), SColl(Box::new(SByte))],
                t_range: Box::new(SOption(Box::new(SColl(Box::new(SByte))))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 11) => (
            SFunc {
                t_dom: vec![
                    SAvlTree,
                    SColl(Box::new(SColl(Box::new(SByte)))),
                    SColl(Box::new(SByte)),
                ],
                t_range: Box::new(SColl(Box::new(SOption(Box::new(SColl(Box::new(SByte))))))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 12) => (
            SFunc {
                t_dom: vec![
                    SAvlTree,
                    SColl(Box::new(STuple(vec![
                        SColl(Box::new(SByte)),
                        SColl(Box::new(SByte)),
                    ]))),
                    SColl(Box::new(SByte)),
                ],
                t_range: Box::new(SOption(Box::new(SAvlTree))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 13) => (
            SFunc {
                t_dom: vec![
                    SAvlTree,
                    SColl(Box::new(STuple(vec![
                        SColl(Box::new(SByte)),
                        SColl(Box::new(SByte)),
                    ]))),
                    SColl(Box::new(SByte)),
                ],
                t_range: Box::new(SOption(Box::new(SAvlTree))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 14) => (
            SFunc {
                t_dom: vec![
                    SAvlTree,
                    SColl(Box::new(SColl(Box::new(SByte)))),
                    SColl(Box::new(SByte)),
                ],
                t_range: Box::new(SOption(Box::new(SAvlTree))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 15) => (
            SFunc {
                t_dom: vec![SAvlTree, SColl(Box::new(SByte))],
                t_range: Box::new(SAvlTree),
                tpe_params: vec![],
            },
            vec![],
        ),
        (100, 16) => (
            SFunc {
                t_dom: vec![
                    SAvlTree,
                    SColl(Box::new(STuple(vec![
                        SColl(Box::new(SByte)),
                        SColl(Box::new(SByte)),
                    ]))),
                    SColl(Box::new(SByte)),
                ],
                t_range: Box::new(SOption(Box::new(SAvlTree))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 1) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 2) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 3) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 4) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 5) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SAvlTree),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 6) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 7) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 8) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 9) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 10) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 11) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SGroupElement),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 12) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SGroupElement),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 13) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 14) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 15) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (104, 16) => (
            SFunc {
                t_dom: vec![SHeader],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (105, 1) => (
            SFunc {
                t_dom: vec![SPreHeader],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (105, 2) => (
            SFunc {
                t_dom: vec![SPreHeader],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (105, 3) => (
            SFunc {
                t_dom: vec![SPreHeader],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (105, 4) => (
            SFunc {
                t_dom: vec![SPreHeader],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (105, 5) => (
            SFunc {
                t_dom: vec![SPreHeader],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (105, 6) => (
            SFunc {
                t_dom: vec![SPreHeader],
                t_range: Box::new(SGroupElement),
                tpe_params: vec![],
            },
            vec![],
        ),
        (105, 7) => (
            SFunc {
                t_dom: vec![SPreHeader],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (106, 1) => (
            SFunc {
                t_dom: vec![SGlobal],
                t_range: Box::new(SGroupElement),
                tpe_params: vec![],
            },
            vec![],
        ),
        (106, 2) => (
            SFunc {
                t_dom: vec![SGlobal, SColl(Box::new(SByte)), SColl(Box::new(SByte))],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (106, 3) => (
            SFunc {
                t_dom: vec![SGlobal, STypeVar("T".into())],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (106, 8) => (
            SFunc {
                t_dom: vec![
                    SGlobal,
                    SInt,
                    SColl(Box::new(SByte)),
                    SColl(Box::new(SByte)),
                    SColl(Box::new(SByte)),
                    SInt,
                ],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (106, 4) => (
            SFunc {
                t_dom: vec![SGlobal, SColl(Box::new(SByte))],
                t_range: Box::new(STypeVar("T".into())),
                tpe_params: vec![],
            },
            vec![STypeVar("T".into())],
        ),
        (106, 6) => (
            SFunc {
                t_dom: vec![SGlobal, SBigInt],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (106, 7) => (
            SFunc {
                t_dom: vec![SGlobal, SLong],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (106, 5) => (
            SFunc {
                t_dom: vec![SGlobal, SColl(Box::new(SByte))],
                t_range: Box::new(STypeVar("T".into())),
                tpe_params: vec![],
            },
            vec![STypeVar("T".into())],
        ),
        (106, 9) => (
            SFunc {
                t_dom: vec![SGlobal, STypeVar("T".into())],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![STypeVar("T".into())],
        ),
        (106, 10) => (
            SFunc {
                t_dom: vec![SGlobal],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![STypeVar("T".into())],
        ),
        (101, 1) => (
            SFunc {
                t_dom: vec![SContext],
                t_range: Box::new(SColl(Box::new(SBox))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 2) => (
            SFunc {
                t_dom: vec![SContext],
                t_range: Box::new(SColl(Box::new(SHeader))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 3) => (
            SFunc {
                t_dom: vec![SContext],
                t_range: Box::new(SPreHeader),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 4) => (
            SFunc {
                t_dom: vec![SContext],
                t_range: Box::new(SColl(Box::new(SBox))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 5) => (
            SFunc {
                t_dom: vec![SContext],
                t_range: Box::new(SColl(Box::new(SBox))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 6) => (
            SFunc {
                t_dom: vec![SContext],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 7) => (
            SFunc {
                t_dom: vec![SContext],
                t_range: Box::new(SBox),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 8) => (
            SFunc {
                t_dom: vec![SContext],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 9) => (
            SFunc {
                t_dom: vec![SContext],
                t_range: Box::new(SAvlTree),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 10) => (
            SFunc {
                t_dom: vec![SContext],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 11) => (
            SFunc {
                t_dom: vec![SContext, SByte],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (101, 12) => (
            SFunc {
                t_dom: vec![SContext, SShort, SByte],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![STypeVar("T".into())],
        ),
        (12, 1) => (
            SFunc {
                t_dom: vec![SColl(Box::new(STypeVar("IV".into())))],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 2) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SInt,
                    STypeVar("IV".into()),
                ],
                t_range: Box::new(STypeVar("IV".into())),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 3) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SFunc {
                        t_dom: vec![STypeVar("IV".into())],
                        t_range: Box::new(STypeVar("OV".into())),
                        tpe_params: vec![],
                    },
                ],
                t_range: Box::new(SColl(Box::new(STypeVar("OV".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 4) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SFunc {
                        t_dom: vec![STypeVar("IV".into())],
                        t_range: Box::new(SBoolean),
                        tpe_params: vec![],
                    },
                ],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 5) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    STypeVar("OV".into()),
                    SFunc {
                        t_dom: vec![STypeVar("OV".into()), STypeVar("IV".into())],
                        t_range: Box::new(STypeVar("OV".into())),
                        tpe_params: vec![],
                    },
                ],
                t_range: Box::new(STypeVar("OV".into())),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 6) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SFunc {
                        t_dom: vec![STypeVar("IV".into())],
                        t_range: Box::new(SBoolean),
                        tpe_params: vec![],
                    },
                ],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 7) => (
            SFunc {
                t_dom: vec![SColl(Box::new(STypeVar("IV".into()))), SInt, SInt],
                t_range: Box::new(SColl(Box::new(STypeVar("IV".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 8) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SFunc {
                        t_dom: vec![STypeVar("IV".into())],
                        t_range: Box::new(SBoolean),
                        tpe_params: vec![],
                    },
                ],
                t_range: Box::new(SColl(Box::new(STypeVar("IV".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 9) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SColl(Box::new(STypeVar("IV".into()))),
                ],
                t_range: Box::new(SColl(Box::new(STypeVar("IV".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 10) => (
            SFunc {
                t_dom: vec![SColl(Box::new(STypeVar("IV".into()))), SInt],
                t_range: Box::new(STypeVar("IV".into())),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 14) => (
            SFunc {
                t_dom: vec![SColl(Box::new(STypeVar("IV".into())))],
                t_range: Box::new(SColl(Box::new(SInt))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 15) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SFunc {
                        t_dom: vec![STypeVar("IV".into())],
                        t_range: Box::new(SColl(Box::new(STypeVar("OV".into())))),
                        tpe_params: vec![],
                    },
                ],
                t_range: Box::new(SColl(Box::new(STypeVar("OV".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 19) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SInt,
                    SColl(Box::new(STypeVar("IV".into()))),
                    SInt,
                ],
                t_range: Box::new(SColl(Box::new(STypeVar("IV".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 20) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SInt,
                    STypeVar("IV".into()),
                ],
                t_range: Box::new(SColl(Box::new(STypeVar("IV".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 21) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SColl(Box::new(SInt)),
                    SColl(Box::new(STypeVar("IV".into()))),
                ],
                t_range: Box::new(SColl(Box::new(STypeVar("IV".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 26) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    STypeVar("IV".into()),
                    SInt,
                ],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 29) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SColl(Box::new(STypeVar("OV".into()))),
                ],
                t_range: Box::new(SColl(Box::new(STuple(vec![
                    STypeVar("IV".into()),
                    STypeVar("OV".into()),
                ])))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 30) => (
            SFunc {
                t_dom: vec![SColl(Box::new(STypeVar("IV".into())))],
                t_range: Box::new(SColl(Box::new(STypeVar("IV".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 31) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SColl(Box::new(STypeVar("IV".into()))),
                ],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 32) => (
            SFunc {
                t_dom: vec![
                    SColl(Box::new(STypeVar("IV".into()))),
                    SColl(Box::new(STypeVar("IV".into()))),
                ],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (12, 33) => (
            SFunc {
                t_dom: vec![SColl(Box::new(STypeVar("IV".into()))), SInt],
                t_range: Box::new(SOption(Box::new(STypeVar("IV".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (36, 2) => (
            SFunc {
                t_dom: vec![SOption(Box::new(STypeVar("T".into())))],
                t_range: Box::new(SBoolean),
                tpe_params: vec![],
            },
            vec![],
        ),
        (36, 3) => (
            SFunc {
                t_dom: vec![SOption(Box::new(STypeVar("T".into())))],
                t_range: Box::new(STypeVar("T".into())),
                tpe_params: vec![],
            },
            vec![],
        ),
        (36, 4) => (
            SFunc {
                t_dom: vec![
                    SOption(Box::new(STypeVar("T".into()))),
                    STypeVar("T".into()),
                ],
                t_range: Box::new(STypeVar("T".into())),
                tpe_params: vec![],
            },
            vec![],
        ),
        (36, 7) => (
            SFunc {
                t_dom: vec![
                    SOption(Box::new(STypeVar("T".into()))),
                    SFunc {
                        t_dom: vec![STypeVar("T".into())],
                        t_range: Box::new(STypeVar("R".into())),
                        tpe_params: vec![],
                    },
                ],
                t_range: Box::new(SOption(Box::new(STypeVar("R".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (36, 8) => (
            SFunc {
                t_dom: vec![
                    SOption(Box::new(STypeVar("T".into()))),
                    SFunc {
                        t_dom: vec![STypeVar("T".into())],
                        t_range: Box::new(SBoolean),
                        tpe_params: vec![],
                    },
                ],
                t_range: Box::new(SOption(Box::new(STypeVar("T".into())))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 1) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt],
                t_range: Box::new(SByte),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 2) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt],
                t_range: Box::new(SShort),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 3) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt],
                t_range: Box::new(SInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 4) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt],
                t_range: Box::new(SLong),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 5) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 6) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt],
                t_range: Box::new(SColl(Box::new(SByte))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 7) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt],
                t_range: Box::new(SColl(Box::new(SBoolean))),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 8) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 9) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt, SUnsignedBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 10) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt, SUnsignedBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 11) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt, SUnsignedBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 12) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt, SInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 13) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt, SInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 14) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt, SUnsignedBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 15) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt, SUnsignedBigInt, SUnsignedBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 16) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt, SUnsignedBigInt, SUnsignedBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 17) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt, SUnsignedBigInt, SUnsignedBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 18) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt, SUnsignedBigInt],
                t_range: Box::new(SUnsignedBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        (9, 19) => (
            SFunc {
                t_dom: vec![SUnsignedBigInt],
                t_range: Box::new(SBigInt),
                tpe_params: vec![],
            },
            vec![],
        ),
        _ => return None,
    })
}
