//! Fresh external vectors generated by scripts/jvm_wallet_oracle/WalletOracle.scala.
use ergo_wallet::encryption::{decrypt, derive_key_pbkdf2, encrypt};

#[test]
fn scala_aes_pbkdf2_vectors_match_field_layout_and_decrypt() {
    let vectors: serde_json::Value = serde_json::from_str(include_str!(
        "../../../test-vectors/wallet/scala_6_0_6.json"
    ))
    .unwrap();
    for vector in vectors["aes"].as_array().unwrap() {
        let salt = hex::decode(vector["salt"].as_str().unwrap()).unwrap();
        let iv: [u8; 12] = hex::decode(vector["iv"].as_str().unwrap())
            .unwrap()
            .try_into()
            .unwrap();
        let plaintext = hex::decode(vector["plaintext"].as_str().unwrap()).unwrap();
        let key = derive_key_pbkdf2(
            vector["password"].as_str().unwrap().as_bytes(),
            &salt,
            128000,
        );
        let (ciphertext, tag) = encrypt(&key, &iv, &plaintext).unwrap();
        assert_eq!(
            hex::encode(&ciphertext),
            vector["cipherText"].as_str().unwrap()
        );
        assert_eq!(hex::encode(tag), vector["authTag"].as_str().unwrap());
        assert_eq!(&*decrypt(&key, &iv, &ciphertext, &tag).unwrap(), &plaintext);
    }
}
