package org.ergoplatform.nodeView.history.storage.modifierprocessors

import java.io.PrintWriter
import java.nio.file.{Files, Paths}

import org.ergoplatform.modifiers.history.header.Header
import org.ergoplatform.settings.{ErgoSettings, ErgoSettingsReader}

/** Runtime oracle harness for [[FullBlockPruningProcessor.updateBestFullBlock]].
  *
  * Reads `prune-formula-vectors.json` (path from the first CLI arg),
  * drives the real upstream processor over each input tuple, captures the
  * resulting `minimalFullBlockHeight`, and writes a `runtime-vectors.json`
  * next to the input. The Rust parity test consumes the runtime output
  * directly so a re-extraction picks up any future Scala-side behavior
  * change.
  *
  * For each input row we build a fresh trait instance backed by a mutable
  * `Int` sentinel and a custom `settings` override that injects the test
  * `blocksToKeep`, `utxoBootstrap`, and `votingLength` values. The
  * `Header` argument is a stub built via `Header.copy` from a real header
  * with only the height overridden — the processor only reads
  * `header.height`.
  */
object PruneFormulaOracle {

  private final case class Inputs(
      currentMin: Int,
      headerHeight: Int,
      blocksToKeep: Int,
      votingLength: Int,
      utxoBootstrap: Boolean
  )

  private final case class Vector(id: String, inputs: Inputs, scalaExpected: Int)

  private final case class Provenance(gitSha: String, gitBranch: String, describe: String, timestamp: String)

  private def readProvenance(): Provenance = {
    def run(args: String*): String = {
      try {
        val pb = new ProcessBuilder(args: _*)
        pb.redirectErrorStream(true)
        val proc = pb.start()
        val out = scala.io.Source.fromInputStream(proc.getInputStream).mkString.trim
        proc.waitFor()
        if (proc.exitValue() == 0) out else "<unavailable>"
      } catch {
        case _: Throwable => "<unavailable>"
      }
    }
    val sha = run("git", "rev-parse", "HEAD")
    val branch = run("git", "rev-parse", "--abbrev-ref", "HEAD")
    val describe = run("git", "describe", "--always", "--dirty")
    val ts = java.time.OffsetDateTime.now(java.time.ZoneOffset.UTC)
      .format(java.time.format.DateTimeFormatter.ISO_OFFSET_DATE_TIME)
    Provenance(sha, branch, describe, ts)
  }

  def main(args: Array[String]): Unit = {
    require(args.length >= 2, "usage: PruneFormulaOracle <input-vectors.json> <output-runtime-vectors.json>")
    val inputPath  = Paths.get(args(0))
    val outputPath = Paths.get(args(1))

    val raw = new String(Files.readAllBytes(inputPath), "UTF-8")
    val rows = parseInputs(raw)

    val baseSettings: ErgoSettings = ErgoSettingsReader.read()

    val provenance = readProvenance()
    val out = new StringBuilder
    out.append("{\n")
    out.append("  \"$schema_version\": 1,\n")
    out.append("  \"oracle_type\": \"scala-runtime\",\n")
    out.append("  \"oracle_caveat\": \"Generated by running upstream FullBlockPruningProcessor.updateBestFullBlock against each input tuple.\",\n")
    out.append("  \"source\": \"ergoplatform/ergo @ src/main/scala/org/ergoplatform/nodeView/history/storage/modifierprocessors/FullBlockPruningProcessor.scala\",\n")
    out.append(s"""  "provenance": {"upstream_git_sha": "${provenance.gitSha}", "upstream_git_branch": "${provenance.gitBranch}", "upstream_describe": "${provenance.describe}", "generated_at_utc": "${provenance.timestamp}"},\n""")
    out.append("  \"vectors\": [\n")
    val emitted = rows.zipWithIndex.map { case (row, idx) =>
      val sentinel = new java.util.concurrent.atomic.AtomicInteger(row.inputs.currentMin)
      val processor = mkProcessor(baseSettings, row.inputs, sentinel)
      val header = mkHeader(row.inputs.headerHeight)
      val written = processor.updateBestFullBlock(header)
      val suffix = if (idx == rows.length - 1) "" else ","
      s"""    {"id": "${row.id}", "inputs": {"current_min": ${row.inputs.currentMin}, "header_height": ${row.inputs.headerHeight}, "blocks_to_keep": ${row.inputs.blocksToKeep}, "voting_length": ${row.inputs.votingLength}, "utxo_bootstrap": ${row.inputs.utxoBootstrap}}, "scala_runtime_output": $written}$suffix"""
    }
    out.append(emitted.mkString("\n"))
    out.append("\n  ]\n")
    out.append("}\n")

    val w = new PrintWriter(outputPath.toFile, "UTF-8")
    try w.write(out.toString) finally w.close()
    println(s"wrote ${rows.length} runtime vectors to $outputPath")
  }

  /** Build a one-shot processor whose `settings` reflects the test
    * inputs and whose minimal-full-block-height read/write hits an
    * `AtomicInteger`.
    */
  private def mkProcessor(
      base: ErgoSettings,
      inputs: Inputs,
      sentinelRef: java.util.concurrent.atomic.AtomicInteger
  ): FullBlockPruningProcessor with MinimalFullBlockHeightFunctions = {
    val nodeWithBtk   = base.nodeSettings.copy(blocksToKeep = inputs.blocksToKeep)
    val nodeWithUtxo  = nodeWithBtk.copy(utxoSettings = nodeWithBtk.utxoSettings.copy(utxoBootstrap = inputs.utxoBootstrap))
    val votingWith    = base.chainSettings.voting.copy(votingLength = inputs.votingLength)
    val chainWith     = base.chainSettings.copy(voting = votingWith)
    val patched       = base.copy(nodeSettings = nodeWithUtxo, chainSettings = chainWith)

    new FullBlockPruningProcessor with MinimalFullBlockHeightFunctions {
      override protected def settings: ErgoSettings = patched
      override def readMinimalFullBlockHeight(): Int = sentinelRef.get()
      override def writeMinimalFullBlockHeight(height: Int): Unit = sentinelRef.set(height)
    }
  }

  /** A header whose only field the processor reads is `height`. */
  private def mkHeader(height: Int): Header = {
    // Construct a minimal Header instance by reflection-free copy of an
    // existing one. We rely on Header being a case class with a height
    // field — true in upstream as of the FullBlockPruningProcessor.scala
    // copy we keep next to this harness.
    Header(
      version = 1.toByte,
      parentId = scorex.util.bytesToId(new Array[Byte](32)),
      ADProofsRoot = scorex.crypto.hash.Digest32 @@ new Array[Byte](32),
      transactionsRoot = scorex.crypto.hash.Digest32 @@ new Array[Byte](32),
      stateRoot = scorex.crypto.authds.ADDigest @@ new Array[Byte](33),
      timestamp = 0L,
      nBits = 0L,
      height = height,
      extensionRoot = scorex.crypto.hash.Digest32 @@ new Array[Byte](32),
      powSolution = null,
      votes = new Array[Byte](3),
      sizeOpt = Some(0),
      unparsedBytes = Array.empty[Byte]
    )
  }

  // Minimal JSON parser tuned to our fixture shape. Avoids pulling in a
  // JSON dependency we don't otherwise need.
  private def parseInputs(json: String): Seq[Vector] = {
    val convergentSection = section(json, "convergent_vectors")
    val divergentSection  = section(json, "divergent_vectors")
    val all = entries(convergentSection) ++ entries(divergentSection)
    all.map { obj =>
      val id   = strField(obj, "id")
      val inp  = subObject(obj, "inputs")
      val cm   = intField(inp, "current_min")
      val hh   = intField(inp, "header_height")
      val btk  = intField(inp, "blocks_to_keep")
      val vl   = intField(inp, "voting_length")
      // utxo_bootstrap field is optional in the input fixture;
      // default to false (the common Mode 1 / Mode 3 path).
      val ub   = optBoolField(inp, "utxo_bootstrap").getOrElse(false)
      val expected = optIntField(obj, "expected")
        .orElse(optIntField(obj, "scala_expected"))
        .getOrElse(Int.MinValue)
      Vector(id, Inputs(cm, hh, btk, vl, ub), expected)
    }
  }

  private def section(json: String, name: String): String = {
    val key = "\"" + name + "\""
    val keyIdx = json.indexOf(key)
    require(keyIdx >= 0, s"section $name missing from input json")
    val openIdx = json.indexOf('[', keyIdx)
    val closeIdx = matchingBracket(json, openIdx, '[', ']')
    json.substring(openIdx + 1, closeIdx)
  }

  private def entries(arr: String): Seq[String] = {
    val out = scala.collection.mutable.ArrayBuffer.empty[String]
    var i = 0
    while (i < arr.length) {
      if (arr.charAt(i) == '{') {
        val end = matchingBracket(arr, i, '{', '}')
        out.append(arr.substring(i, end + 1))
        i = end + 1
      } else i += 1
    }
    out.toSeq
  }

  private def matchingBracket(s: String, openIdx: Int, open: Char, close: Char): Int = {
    var depth = 1
    var i = openIdx + 1
    var inString = false
    while (i < s.length && depth > 0) {
      val c = s.charAt(i)
      if (c == '"' && (i == 0 || s.charAt(i - 1) != '\\')) inString = !inString
      else if (!inString) {
        if (c == open) depth += 1
        else if (c == close) depth -= 1
      }
      if (depth > 0) i += 1
    }
    require(depth == 0, "unbalanced brackets in JSON")
    i
  }

  private def subObject(obj: String, key: String): String = {
    val k = "\"" + key + "\""
    val kIdx = obj.indexOf(k)
    require(kIdx >= 0, s"key $key missing")
    val open = obj.indexOf('{', kIdx)
    val close = matchingBracket(obj, open, '{', '}')
    obj.substring(open, close + 1)
  }

  private def strField(obj: String, key: String): String = {
    val k = "\"" + key + "\""
    val kIdx = obj.indexOf(k)
    require(kIdx >= 0, s"key $key missing")
    val open = obj.indexOf('"', kIdx + k.length + 1) + 1
    val close = obj.indexOf('"', open)
    obj.substring(open, close)
  }

  private def intField(obj: String, key: String): Int = optIntField(obj, key).getOrElse(
    throw new IllegalArgumentException(s"required int field $key missing")
  )

  private def optIntField(obj: String, key: String): Option[Int] = {
    val k = "\"" + key + "\""
    val kIdx = obj.indexOf(k)
    if (kIdx < 0) return None
    val colon = obj.indexOf(':', kIdx + k.length)
    if (colon < 0) return None
    var i = colon + 1
    while (i < obj.length && obj.charAt(i).isWhitespace) i += 1
    val start = i
    if (i < obj.length && obj.charAt(i) == '-') i += 1
    while (i < obj.length && obj.charAt(i).isDigit) i += 1
    if (i == start) None else Some(obj.substring(start, i).toInt)
  }

  private def optBoolField(obj: String, key: String): Option[Boolean] = {
    val k = "\"" + key + "\""
    val kIdx = obj.indexOf(k)
    if (kIdx < 0) return None
    val colon = obj.indexOf(':', kIdx + k.length)
    if (colon < 0) return None
    var i = colon + 1
    while (i < obj.length && obj.charAt(i).isWhitespace) i += 1
    if (obj.substring(i).startsWith("true")) Some(true)
    else if (obj.substring(i).startsWith("false")) Some(false)
    else None
  }
}
