//> using repository "https://gitlab.com/api/v4/projects/61211221/packages/maven"
//> using scala 2.12
//> using dep org.scorexfoundation::sigma-state:6.0.2

// Scala AVL+ verifier ORACLE for the Rust node's `ergo_sigma::avl::AvlVerifier`.
//
// Emits a JSON array of differential vectors to stdout. Each vector pins, for a
// (startingDigest, proof, op) triple, the AUTHORITATIVE Scala scrypto
// BatchAVLVerifier outcome: whether `performOneOperation` succeeds and the
// resulting `digest`. The Rust test `avl_scala_oracle_parity.rs` then asserts
// `AvlVerifier` agrees — Scala-success+digest <=> Rust Ok + same digest, and
// Scala-failure <=> Rust failure (the reject-valid / accept-invalid guard).
//
// Proofs are generated by the SCALA prover, so this is a true verifier
// differential with no dependence on Rust-prover/Scala-prover byte parity.
//
// Regenerate (commits to test-vectors/ergo-sigma/avl-proof-parity/):
//   scala-cli run scripts/avl_oracle/AvlOracle.scala \
//     > test-vectors/ergo-sigma/avl-proof-parity/scala_avl_vectors.json
import scorex.crypto.authds.{ADKey, ADValue, ADDigest, SerializedAdProof}
import scorex.crypto.authds.avltree.batch.{
  BatchAVLProver, BatchAVLVerifier, Insert, Update, Remove, Lookup, Operation
}
import scorex.crypto.hash.{Blake2b256, Digest32}

object AvlOracle {
  def hex(b: Array[Byte]): String = b.map(x => f"${x & 0xff}%02x").mkString

  def valueFor(vl: Option[Int]): Array[Byte] = vl match {
    case Some(n) => Array.fill(n)(0xAB.toByte)
    case None    => Array[Byte](0xAB.toByte, 0xCD.toByte)
  }

  // Distinct payload for UPDATE vectors: the leaf value must actually change vs
  // the `valueFor`-seeded insert, otherwise the update is a no-op and the
  // expected digest equals the start digest (it would not exercise a real
  // digest change). Same length as `valueFor` so fixed-length trees stay valid.
  def updateValueFor(vl: Option[Int]): Array[Byte] = vl match {
    case Some(n) => Array.fill(n)(0x5A.toByte)
    case None    => Array[Byte](0x12.toByte, 0x34.toByte)
  }

  def opJson(op: Operation): String = {
    val (kind, k, v) = op match {
      case Lookup(key)    => ("lookup", key: Array[Byte], None)
      case Remove(key)    => ("remove", key: Array[Byte], None)
      case Insert(key, x) => ("insert", key: Array[Byte], Some(x: Array[Byte]))
      case Update(key, x) => ("update", key: Array[Byte], Some(x: Array[Byte]))
      case other          => ("other", other.key: Array[Byte], None)
    }
    val vJson = v.map(x => "\"" + hex(x) + "\"").getOrElse("null")
    s"""{"kind":"$kind","keyHex":"${hex(k)}","valueHex":$vJson}"""
  }

  /** Build a tree of `keys`, capture the start digest, apply `proofOp` to the
    * prover, then VERIFY `verifyOp` against the generated proof. Optionally
    * corrupt the proof bytes first. Returns one JSON vector. */
  def gen(
      name: String,
      keys: Seq[Array[Byte]],
      proofOp: Operation,
      verifyOp: Operation,
      vl: Option[Int],
      corrupt: Array[Byte] => Array[Byte] = identity
  ): String = {
    val prover = new BatchAVLProver[Digest32, Blake2b256.type](keyLength = 32, valueLengthOpt = vl)
    keys.foreach(k => prover.performOneOperation(Insert(ADKey @@ k, ADValue @@ valueFor(vl))))
    prover.generateProof()
    val start: ADDigest = prover.digest
    prover.performOneOperation(proofOp) // may legitimately fail; proof still witnesses the path
    val proof: SerializedAdProof = SerializedAdProof @@ corrupt(prover.generateProof())

    val verifier = new BatchAVLVerifier[Digest32, Blake2b256.type](
      start, proof, keyLength = 32, valueLengthOpt = vl, maxNumOperations = None, maxDeletes = None)
    val res = verifier.performOneOperation(verifyOp)
    val success = res.isSuccess
    val digest = verifier.digest // None on any failure (Scala topNode = None)

    val vlJson = vl.map(_.toString).getOrElse("null")
    val digJson = digest.map(d => "\"" + hex(d) + "\"").getOrElse("null")
    s"""{"name":"$name","keyLength":32,"valueLength":$vlJson,""" +
      s""""startDigestHex":"${hex(start)}","proofHex":"${hex(proof)}",""" +
      s""""op":${opJson(verifyOp)},""" +
      s""""expect":{"success":$success,"digestHex":$digJson}}"""
  }

  def key(i: Int): Array[Byte] = Array.fill(32)((i + 1).toByte) // 1..N, never the 0x00/0xFF sentinels
  val absent: Array[Byte] = Array.fill(32)(0x7e.toByte)

  def main(args: Array[String]): Unit = {
    val out = scala.collection.mutable.ArrayBuffer[String]()

    for (n <- 1 to 16) {
      val keys = (0 until n).map(key)
      val present = keys(n / 2)
      // VALID accept cases — across tree shapes, exercising rebalancing/deleteMax
      // on a correct proof. These close the "Scala accepts, Rust panics" gap.
      out += gen(s"valid_lookup_n$n", keys, Lookup(ADKey @@ present), Lookup(ADKey @@ present), None)
      out += gen(s"valid_remove_n$n", keys, Remove(ADKey @@ present), Remove(ADKey @@ present), None)
      // WRONG-OP REPLAY — a valid lookup proof used for a remove. This is the
      // Rust op-time panic class; Scala fails closed (Failure / digest None).
      out += gen(s"lookupproof_remove_n$n", keys, Lookup(ADKey @@ present), Remove(ADKey @@ present), None)
      // Remove of an ABSENT key against a present-key lookup proof — off the
      // witnessed path; Scala failure.
      out += gen(s"remove_absent_n$n", keys, Lookup(ADKey @@ present), Remove(ADKey @@ absent), None)
    }

    // Insert / update accept cases.
    for (n <- 1 to 6) {
      val keys = (0 until n).map(key)
      val fresh = key(100 + n)
      val present = keys(n / 2)
      out += gen(s"valid_insert_n$n", keys, Insert(ADKey @@ fresh, ADValue @@ valueFor(None)),
        Insert(ADKey @@ fresh, ADValue @@ valueFor(None)), None)
      out += gen(s"valid_update_n$n", keys, Update(ADKey @@ present, ADValue @@ updateValueFor(None)),
        Update(ADKey @@ present, ADValue @@ updateValueFor(None)), None)
    }

    // Fixed value-length variant (valueLengthOpt = Some(4)).
    for (n <- 1 to 8) {
      val keys = (0 until n).map(key)
      val present = keys(n / 2)
      out += gen(s"valid_remove_fixedval_n$n", keys, Remove(ADKey @@ present), Remove(ADKey @@ present), Some(4))
      out += gen(s"lookupproof_remove_fixedval_n$n", keys, Lookup(ADKey @@ present), Remove(ADKey @@ present), Some(4))
    }

    // Malformed-but-constructible proofs — Scala fails (reconstruction or replay).
    for (n <- 2 to 8) {
      val keys = (0 until n).map(key)
      val present = keys(n / 2)
      out += gen(s"truncated_proof_n$n", keys, Remove(ADKey @@ present), Remove(ADKey @@ present), None,
        p => p.take(p.length / 2))
      out += gen(s"flipped_proof_n$n", keys, Remove(ADKey @@ present), Remove(ADKey @@ present), None,
        p => { val q = p.clone(); if (q.nonEmpty) q(q.length / 3) = (q(q.length / 3) ^ 0xFF).toByte; q })
    }

    println("[\n  " + out.mkString(",\n  ") + "\n]")
  }
}
