//! Sigma-protocol hint types per Scala `sigmastate.interpreter.HintsBag` +
//! `org.ergoplatform.wallet.interpreter.TransactionHintsBag`.
//!
//! In single-sig signing, the bag is empty: the prover holds all secrets
//! and generates its own commitments + responses. In multi-sig,
//! cooperating parties exchange `OwnCommitment` (the secret commitment
//! they generated locally) and `RealCommitment` (public part to publish);
//! the final signer aggregates commitments and challenges into the bag
//! before calling `Prover::sign`.

use ergo_ser::sigma_value::SigmaBoolean;
use std::collections::BTreeMap;

use crate::proving::node_position::NodePosition;

/// First-prover message: the commitment a prover broadcasts at the start
/// of a sigma protocol. Mirrors sigma-rust's `FirstProverMessage` enum.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FirstProverMessage {
    /// Schnorr commitment `R = g^r` (33-byte SEC1 compressed).
    Schnorr([u8; 33]),
    /// DH-tuple commitment `(A, B) = (g^r, h^r)` — two compressed points.
    DhTuple { a: [u8; 33], b: [u8; 33] },
}

/// A hint carries information from cooperating parties needed to produce
/// a partial or full sigma proof.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Hint {
    /// Own randomness for a sigma leaf this prover knows the secret for.
    /// Generated locally during commitment-generation; kept private until
    /// signing (multi-sig). Single-sig: generated and consumed in one step.
    OwnCommitment(OwnCommitment),

    /// Public commitment for a leaf — what other parties learn about
    /// this prover's commitment so they can include it in their
    /// Fiat-Shamir challenge computation.
    RealCommitment(RealCommitment),

    /// Simulated commitment for a leaf in an OR-branch the prover does
    /// NOT know the secret for. Generated by the prover at sign time.
    SimulatedCommitment(SimulatedCommitment),

    /// Real proof (challenge + response) for a sigma leaf this prover signed.
    /// Distributed to other parties so they can verify their own positions.
    RealSecretProof(RealSecretProof),

    /// Simulated proof for an OR-branch the prover doesn't know.
    SimulatedSecretProof(SimulatedSecretProof),
}

/// Own randomness commitment for a leaf. `image` is the sigma boolean
/// (e.g. `ProveDlog(pk)`) the commitment is for; `secret_randomness` is
/// the scalar `r` used to compute the commitment(s). `commitment` carries
/// the public first-prover message (Schnorr: `R = g^r`; DHT: `(A, B) = (g^r, h^r)`).
/// `position` disambiguates duplicate leaves in asymmetric trees.
#[derive(Clone, PartialEq, Eq)]
pub struct OwnCommitment {
    pub image: SigmaBoolean,
    /// `r` in scalar form — must NEVER leak (compromises the secret on reveal).
    pub secret_randomness: [u8; 32],
    /// Public first-prover message corresponding to `r`.
    pub commitment: FirstProverMessage,
    /// Position of this leaf in the proposition tree (depth-first).
    pub position: NodePosition,
}

impl std::fmt::Debug for OwnCommitment {
    // Hand-written so the secret scalar `r` never reaches a log line or a
    // `{:?}` dump: deriving Debug would print `secret_randomness`, and
    // `Hint`'s derived Debug forwards to this impl. Revealing `r` together
    // with the public challenge/response recovers the private key.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("OwnCommitment")
            .field("image", &self.image)
            .field("secret_randomness", &"[REDACTED]")
            .field("commitment", &self.commitment)
            .field("position", &self.position)
            .finish()
    }
}

/// Real commitment (public). The public mirror of `OwnCommitment::commitment`
/// without the `secret_randomness` — what gets distributed in multi-sig.
/// `position` disambiguates duplicate leaves in asymmetric trees.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RealCommitment {
    pub image: SigmaBoolean,
    pub commitment: FirstProverMessage,
    pub position: NodePosition,
}

/// Simulated commitment for an OR-branch the prover can't prove.
/// In OR-composition, the prover picks the OR branch they CAN prove and
/// generates real commitments for it; for branches they can't prove,
/// they simulate (pick a random challenge + response, derive the
/// commitment back-mathematically). `position` disambiguates duplicates.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SimulatedCommitment {
    pub image: SigmaBoolean,
    pub commitment: FirstProverMessage,
    pub challenge: [u8; 24],
    pub position: NodePosition,
}

/// A real proof (challenge + response) for a sigma leaf.
/// `position` disambiguates duplicate leaves in asymmetric trees.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RealSecretProof {
    pub image: SigmaBoolean,
    pub challenge: [u8; 24],
    pub response: [u8; 32],
    pub position: NodePosition,
}

/// A simulated proof.
/// `position` disambiguates duplicate leaves in asymmetric trees.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SimulatedSecretProof {
    pub image: SigmaBoolean,
    pub challenge: [u8; 24],
    pub response: [u8; 32],
    pub position: NodePosition,
}

/// Per-input collection of hints. Mirrors Scala
/// `sigmastate.interpreter.HintsBag(hints: Seq[Hint])`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct HintsBag {
    pub hints: Vec<Hint>,
}

impl HintsBag {
    pub const fn empty() -> Self {
        Self { hints: Vec::new() }
    }

    pub fn add(&mut self, hint: Hint) {
        self.hints.push(hint);
    }

    pub fn extend(&mut self, other: HintsBag) {
        self.hints.extend(other.hints);
    }

    /// Partition into (secret, public) per Scala
    /// `TransactionHintsBag.replaceHintsForInput`:
    /// secrets are `OwnCommitment`; public is everything else.
    pub fn partition(self) -> (HintsBag, HintsBag) {
        let mut secret = HintsBag::empty();
        let mut public = HintsBag::empty();
        for h in self.hints {
            if matches!(h, Hint::OwnCommitment(_)) {
                secret.hints.push(h);
            } else {
                public.hints.push(h);
            }
        }
        (secret, public)
    }
}

/// Per-tx-input hints, partitioned into secret + public per Scala
/// `TransactionHintsBag(secretHints: Map[Int, HintsBag], publicHints: Map[Int, HintsBag])`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct TransactionHintsBag {
    pub secret_hints: BTreeMap<u32, HintsBag>,
    pub public_hints: BTreeMap<u32, HintsBag>,
}

impl TransactionHintsBag {
    pub const fn empty() -> Self {
        Self {
            secret_hints: BTreeMap::new(),
            public_hints: BTreeMap::new(),
        }
    }

    /// Replace hints for the given input index.
    /// Mirrors Scala `replaceHintsForInput`.
    pub fn replace_for_input(&mut self, index: u32, bag: HintsBag) {
        let (secret, public) = bag.partition();
        self.secret_hints.insert(index, secret);
        self.public_hints.insert(index, public);
    }

    /// Add hints for the given input index (preserves existing).
    /// Mirrors Scala `addHintsForInput`.
    pub fn add_for_input(&mut self, index: u32, bag: HintsBag) {
        let (secret, public) = bag.partition();
        let s = self.secret_hints.entry(index).or_default();
        s.extend(secret);
        let p = self.public_hints.entry(index).or_default();
        p.extend(public);
    }

    /// Combined (secret + public) hints for the given input.
    /// Mirrors Scala `allHintsForInput`.
    pub fn all_for_input(&self, index: u32) -> HintsBag {
        let mut combined = HintsBag::empty();
        if let Some(s) = self.secret_hints.get(&index) {
            combined.hints.extend(s.hints.iter().cloned());
        }
        if let Some(p) = self.public_hints.get(&index) {
            combined.hints.extend(p.hints.iter().cloned());
        }
        combined
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_own_commitment() -> OwnCommitment {
        OwnCommitment {
            image: SigmaBoolean::TrivialProp(true),
            secret_randomness: [0xAB; 32],
            commitment: FirstProverMessage::Schnorr([0x02; 33]),
            position: NodePosition::crypto_tree_prefix(),
        }
    }

    #[test]
    fn own_commitment_debug_redacts_secret_randomness() {
        // The derived Debug would have printed the raw nonce as
        // `secret_randomness: [171, 171, ...]`; the hand-written impl prints
        // `[REDACTED]` so the scalar `r` never reaches a log line. Check the
        // struct directly and through every wrapper whose derived Debug
        // forwards to it.
        let oc = sample_own_commitment();
        let raw_nonce = "171, 171, 171"; // Debug of the [0xAB; _] bytes, if leaked

        let direct = format!("{oc:?}");
        assert!(direct.contains("[REDACTED]"), "{direct}");
        assert!(!direct.contains(raw_nonce), "leaked raw nonce: {direct}");

        let via_hint = format!("{:?}", Hint::OwnCommitment(oc.clone()));
        assert!(via_hint.contains("[REDACTED]"), "{via_hint}");
        assert!(!via_hint.contains(raw_nonce), "leaked via Hint: {via_hint}");

        let mut bag = HintsBag::empty();
        bag.add(Hint::OwnCommitment(oc));
        let via_bag = format!("{bag:?}");
        assert!(via_bag.contains("[REDACTED]"), "{via_bag}");
        assert!(
            !via_bag.contains(raw_nonce),
            "leaked via HintsBag: {via_bag}"
        );
    }
}
