//> using scala 2.12
//> using dep org.scorexfoundation::sigma-state:6.0.2
// Emits the complete v6 method signature registry used by static inference.
import sigma.VersionContext
import sigma.ast._
object MethodTypes {
  private val containers: Seq[MethodsContainer] = Seq(
    SByteMethods, SShortMethods, SIntMethods, SLongMethods, SBigIntMethods,
    SBooleanMethods, SStringMethods, SGroupElementMethods, SSigmaPropMethods,
    SBoxMethods, SAvlTreeMethods, SHeaderMethods, SPreHeaderMethods,
    SGlobalMethods, SContextMethods, SCollectionMethods, SOptionMethods,
    STupleMethods, SUnitMethods, SAnyMethods, SUnsignedBigIntMethods
  )


  def rust(t: SType): String = t match {
    case v: STypeVar => "STypeVar(\"" + v.name + "\".into())"
    case c: SCollectionType[_] => "SColl(Box::new(" + rust(c.elemType) + "))"
    case o: SOption[_] => "SOption(Box::new(" + rust(o.elemType) + "))"
    case t: STuple => "STuple(vec![" + t.items.map(rust).mkString(", ") + "])"
    case f: SFunc => "SFunc { t_dom: vec![" + f.tDom.map(rust).mkString(", ") + "], t_range: Box::new(" + rust(f.tRange) + "), tpe_params: vec![] }"
    case _ => t.toString.stripSuffix("$")
  }
  def main(args: Array[String]): Unit = VersionContext.withVersions(3.toByte, 3.toByte) {
    println("//! Generated by scripts/jvm_serde_oracle/MethodTypes.scala; sigma-state 6.0.2.")
    println("use crate::sigma_type::SigmaType;")
    println("pub(super) fn signature(type_id: u8, method_id: u8) -> Option<(SigmaType, Vec<SigmaType>)> {")
    println("use SigmaType::*; Some(match (type_id, method_id) {")
    for (c <- containers; m <- c.methods) {
      println(s"(${m.objType.typeId & 255}, ${m.methodId & 255}) => (" + rust(m.stype) + ", vec![" + m.explicitTypeArgs.map(rust).mkString(", ") + "]),")
    }
    println("_ => return None, }) }")
  }
}
